### ISSUE TITLE
Configurable list of domains where this extension automatically redirects

### ISSUE THREAD

**Issue by felixdv** [brenopoggiali/outline-extension#1]
This is more of a feature request, rather than a bug report.

The way I use outline is that generally, there are a number of domains where I always use the outline tool and other domains where I would never use it. In that way, it would make sense if there is a configurable list of domains where the extension does this process automatically, instead of having to push the button.

Is something like that possible?

**Comment by brenopoggiali** [comment]
Hi Felix,

Thanks for the tip. That would be a really cool feature. Doing a quick search I found that it is possible to implement this! I'm just not sure if I'll be able to implement it this year. Although I try. Anyway, if you want, feel free to open any PRs here including this feature. I can help you reviewing and debugging.

Health,
Breno

**Comment by brenopoggiali** [comment]
Hi Felix,

Thanks for the tip. That would be a really cool feature. Doing a quick search I found that it is possible to implement this! I'm just not sure if I'll be able to implement it this year. Although I'll try. Anyway, if you want, feel free to open any PRs here including this feature. I can help you reviewing and debugging.

Cheers,
Breno

**Comment by brenopoggiali** [comment]
Outline.com has been shut down, I've now created the [12ft redirect](https://chrome.google.com/webstore/detail/12ft-redirect/lkndnkfpgdacnjiolbbmkfpanahchbge/related). Please re-open this issue on the [new repository for this other extension](https://github.com/brenopoggiali/12ft-extension).

Thanks,
Breno
