### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by bjc1958** [brenopoggiali/outline-extension#2]
What happened?  Just error messages for last couple of weeks.

**Comment by brenopoggiali** [comment]
Hi,

Apparently, [Outline.com has been taken down](https://news.ycombinator.com/item?id=30564665). I have adapted this extension for 12ft.io, but I haven't been able to upload it to Chrome Web Store yet because they have migrated the Manifest from 2 to 3, so I need to code everything from scratch again. However, if you want to just clone [the repository](https://github.com/brenopoggiali/12ft-extension) and upload the extension locally, you can do it :) 

Best,
Breno

**Comment by bjc1958** [comment]
I honestly have been trying to figure out how to do this, as you suggested,
since your email to me.  I just have little to no experience or schooling
with this stuff and haven't been able to figure it out.  Think of me like
you would if you have to teach a kid in elementary school.  A kid who got a
computer not that long ago and has had to teach everything to themselves.
I actually learned about downloading scripts from a comment in a blog.  I
had to learn about peer-to-peer downloading the same way.  I learned just
enough to be about to do the downloads but not enough to make any "fixes"
that might be needed.   Just so you know, I'm a 64-year-old woman who
learned about computers from working on CRTs and the big mainframes they
had in the 70s.  By the time personal computers came around, I was in the
workforce and had to teach everything to myself so my employers wouldn't
know that I didn't know a damn thing about personal computers.  I think
that has kept me from advancing to higher levels of knowledge over the
years.

Anything you could tell me how to do step by step would be appreciated more
than you know.

And thank you so much for responding to my first question.  I really did
appreciate that.

Sincerely,
Barbara

**Comment by brenopoggiali** [comment]
Hey Barbara,

I have finished migrating the 12ft extension to V3 and I'm now waiting for it to be approved and published on the Chrome Web Store. I'll update this thread as soon as it is released.

Sorry for taking too long to do it. I hope it helps you :)

Best,
Breno

**Comment by brenopoggiali** [comment]
Hey Barbara,

Sorry for the long delay on sharing it with you. The new extension was published a month ago. You can find it [here](https://chrome.google.com/webstore/detail/12ft-redirect/lkndnkfpgdacnjiolbbmkfpanahchbge/related). It now uses a website called 12ft.io to remove the paywall :) 

I hope you enjoy it! Let me know if you need anything else. 

Best,
Breno
